#pragma once
#include <Windows.h>
#include <iostream>
#include <gdiplus.h>
#include <assert.h>
#include <stdio.h>	
#include <ConsoleApi.h>
#include <algorithm>
#include <string>
#include <vector>
#include <conio.h>
#include <cmath>
#include <fstream>
#include <sstream>